// ==========================================
// DATABASE FRASARIO COMPLETO (CON CATEGORIE)
// ==========================================

const phrasebookDatabase = [
  // 🤝 INCONTRO
  { category: "incontro", it: "Buongiorno.", ja: "おはようございます。", romaji: "Ohayou gozaimasu." },
  { category: "incontro", it: "Ciao! / Buon pomeriggio.", ja: "こんにちは！", romaji: "Konnichiwa!" },
  { category: "incontro", it: "Buonasera.", ja: "こんばんは。", romaji: "Konbanwa." },
  { category: "incontro", it: "Piacere di conoscerti.", ja: "はじめまして。", romaji: "Hajimemashite." },
  { category: "incontro", it: "Come stai?", ja: "お元気ですか？", romaji: "Ogenki desu ka?" },
  { category: "incontro", it: "Sto bene, grazie.", ja: "はい、元気です。ありがとうございます。", romaji: "Hai, genki desu. Arigatou gozaimasu." },
  { category: "incontro", it: "Mi chiamo...", ja: "私の名前は...です。", romaji: "Watashi no namae wa... desu." },
  { category: "incontro", it: "Vengo dall'Italia.", ja: "イタリアから来ました。", romaji: "Itaria kara kimashita." },
  { category: "incontro", it: "Arrivederci.", ja: "さようなら。", romaji: "Sayounara." },
  { category: "incontro", it: "A domani.", ja: "また明日。", romaji: "Mata ashita." },
  { category: "incontro", it: "Buonanotte.", ja: "おやすみなさい。", romaji: "Oyasuminasai." },
  { category: "incontro", it: "Come si chiama?", ja: "お名前は何ですか？", romaji: "Onamae wa nan desu ka?" },
  { category: "incontro", it: "Quanti anni hai?", ja: "何歳ですか？", romaji: "Nansai desu ka?" },
  { category: "incontro", it: "Lavoro come impiegato.", ja: "会社員として働いています。", romaji: "Kaishain toshite hataraite imasu." },
  { category: "incontro", it: "Il mio hobby è ascoltare musica.", ja: "趣味は音楽を聴くことです。", romaji: "Shumi wa ongaku o kiku koto desu." },
  { category: "incontro", it: "Da quanto tempo vivi qui?", ja: "ここに住んでどのくらいですか？", romaji: "Koko ni sunde dono kurai desu ka?" },
  { category: "incontro", it: "È da tanto che non ci vediamo!", ja: "お久しぶりです！", romaji: "Ohisashiburi desu!" },
  { category: "incontro", it: "Buon viaggio!", ja: "良い旅を！", romaji: "Yoi tabi o!" },
  { category: "incontro", it: "Benvenuto!", ja: "いらっしゃいませ！", romaji: "Irasshaimase!" },
  { category: "incontro", it: "Che bel tempo oggi.", ja: "今日はいい天気ですね。", romaji: "Kyou wa ii tenki desu ne." },
  { category: "incontro", it: "Fa freddo, vero?", ja: "寒いですね？", romaji: "Samui desu ne?" },

  // 🗣️ CORTESIA
  { category: "cortesia", it: "Grazie mille.", ja: "どうもありがとうございます。", romaji: "Doumo arigatou gozaimasu." },
  { category: "cortesia", it: "Prego / Di niente.", ja: "どういたしまして。", romaji: "Dou itashimashite." },
  { category: "cortesia", it: "Scusi / Mi scusi.", ja: "すみません。", romaji: "Sumimasen." },
  { category: "cortesia", it: "Mi dispiace / Perdonami.", ja: "ごめんなさい。", romaji: "Gomennasai." },
  { category: "cortesia", it: "Sì.", ja: "はい。", romaji: "Hai." },
  { category: "cortesia", it: "No.", ja: "いいえ。", romaji: "Iie." },
  { category: "cortesia", it: "Non capisco.", ja: "わかりません。", romaji: "Wakarimasen." },
  { category: "cortesia", it: "Ho capito.", ja: "わかりました。", romaji: "Wakarimashita." },
  { category: "cortesia", it: "Parli inglese?", ja: "英語を話せますか？", romaji: "Eigo o hanasemasu ka?" },
  { category: "cortesia", it: "Puoi parlare un po' più piano, per favore?", ja: "もう少しゆっくり話してください。", romaji: "Mou sukoshi yukkuri hanashite kudasai." },
  { category: "cortesia", it: "D'accordo. / Va bene.", ja: "わかりました / 了解です。", romaji: "Wakarimashita / Ryoukai desu." },
  { category: "cortesia", it: "Certo / Naturalmente.", ja: "もちろん。", romaji: "Mochiron." },
  { category: "cortesia", it: "Forse.", ja: "たぶん。", romaji: "Tabun." },
  { category: "cortesia", it: "Un attimo, per favore.", ja: "少々お待ちください。", romaji: "Shoushou omachi kudasai." },
  { category: "cortesia", it: "Non importa.", ja: "気にしないで。", romaji: "Ki ni shinaide." },
  { category: "cortesia", it: "Cosa significa questo?", ja: "これはどういう意味ですか？", romaji: "Kore wa dou iu imi desu ka?" },
  { category: "cortesia", it: "Come si pronuncia?", ja: "これはどう発音しますか？", romaji: "Kore wa dou hatsuon shimasu ka?" },
  { category: "cortesia", it: "Puoi scriverlo, per favore?", ja: "書いてくれますか？", romaji: "Kaite kuremasu ka?" },
  { category: "cortesia", it: "Mi sono sbagliato.", ja: "間違えました。", romaji: "Machigaemashita." },
  { category: "cortesia", it: "Nessun problema.", ja: "問題ありません。", romaji: "Mondai arimasen." },

  // ✈️ VIAGGIO
  { category: "viaggio", it: "Dov'è la stazione ferroviaria?", ja: "駅はどこですか？", romaji: "Eki wa doko desu ka?" },
  { category: "viaggio", it: "Vorrei un biglietto per Tokyo.", ja: "東京までの切符をお願いします。", romaji: "Tokyo made no kippu o onegaishimasu." },
  { category: "viaggio", it: "Da quale binario parte il treno per Osaka?", ja: "大阪行きの電車は何番線から出ますか？", romaji: "Osaka yuki no densha wa nanbansen kara demasu ka?" },
  { category: "viaggio", it: "Questo treno va a Kanazawa?", ja: "この電車は金沢に行きますか？", romaji: "Kono densha wa Kanazawa ni ikimasu ka?" },
  { category: "viaggio", it: "Dov'è la fermata dell'autobus?", ja: "バス停はどこですか？", romaji: "Basutei wa doko desu ka?" },
  { category: "viaggio", it: "Dove posso prendere un taxi?", ja: "どこでタクシーに乗れますか？", romaji: "Doko de takushii ni noremasu ka?" },
  { category: "viaggio", it: "Dov'è la biglietteria?", ja: "切符売り場はどこですか？", romaji: "Kippu uriba wa doko desu ka?" },
  { category: "viaggio", it: "Vorrei prenotare un posto.", ja: "席を予約したいのですが。", romaji: "Seki o yoyaku shitai no desu ga." },
  { category: "viaggio", it: "Questo posto è occupato?", ja: "この席は空いていますか？", romaji: "Kono seki wa aite imasu ka?" },
  { category: "viaggio", it: "Scendo alla prossima fermata.", ja: "次の駅で降ります。", romaji: "Tsugi no eki de orimasu." },
  { category: "viaggio", it: "Dove devo cambiare treno?", ja: "どこで乗り換えですか？", romaji: "Doko de norikae desu ka?" },
  { category: "viaggio", it: "Manca molto per arrivare?", ja: "到着までまだ時間がかかりますか？", romaji: "Touchaku made mada jikan ga kakarimasu ka?" },
  { category: "viaggio", it: "Mi mostri sulla mappa, per favore.", ja: "地図で教えてください。", romaji: "Chizu de oshiete kudasai." },
  { category: "viaggio", it: "Va dritto e poi giri a destra.", ja: "まっすぐ行って、右に曲がってください。", romaji: "Massugu itte, migi ni magatte kudasai." },
  { category: "viaggio", it: "Dov'è l'uscita?", ja: "出口はどこですか？", romaji: "Deguchi wa doko desu ka?" },
  { category: "viaggio", it: "Qual è la password del Wi-Fi?", ja: "Wi-Fiのパスワードは何ですか？", romaji: "Wi-Fi no pasuwaado wa nan desu ka?" },

  // 🍽️ RISTORANTE
  { category: "ristorante", it: "Siamo in due.", ja: "二人です。", romaji: "Futari desu." },
  { category: "ristorante", it: "Avete un menù in inglese?", ja: "英語のメニューはありますか？", romaji: "Eigo no menyuu wa arimasu ka?" },
  { category: "ristorante", it: "Vorrei ordinare questo, per favore.", ja: "これを注文したいです。", romaji: "Kore o chuumon shitai desu." },
  { category: "ristorante", it: "Cosa mi consiglia?", ja: "おすすめは何ですか？", romaji: "Osusume wa nan desu ka?" },
  { category: "ristorante", it: "Da bere, dell'acqua per favore.", ja: "お水をお願いします。", romaji: "Omizu o onegaishimasu." },
  { category: "ristorante", it: "Il conto, per favore.", ja: "お会計をお願いします。", romaji: "Okaikei o onegaishimasu." },
  { category: "ristorante", it: "Un tavolo per quattro, per favore.", ja: "4人用の席をお願いします。", romaji: "Yonin you no seki o onegaishimasu." },
  { category: "ristorante", it: "Avete piatti vegetariani?", ja: "ベジタリアン用のメニューはありますか？", romaji: "Bejitarian you no menyuu wa arimasu ka?" },
  { category: "ristorante", it: "Sono allergico ai crostacei.", ja: "甲殻類アレルギーがあります。", romaji: "Koukakurui arerugii ga arimasu." },
  { category: "ristorante", it: "Senza cipolla, per favore.", ja: "玉ねぎ抜きでお願いします。", romaji: "Tamanegi nuki de onegaishimasu." },
  { category: "ristorante", it: "Cosa c'è in questo piatto?", ja: "この料理には何が入っていますか？", romaji: "Kono ryouri ni wa nani ga haitte imasu ka?" },
  { category: "ristorante", it: "Ancora un po' d'acqua, per favore.", ja: "お水をもう少しください。", romaji: "Omizu o mou sukoshi kudasai." },
  { category: "ristorante", it: "È piccante?", ja: "これは辛いですか？", romaji: "Kore wa karai desu ka?" },
  { category: "ristorante", it: "Posso avere il menù dei dolci?", ja: "デザートのメニューをもらえますか？", romaji: "Dezaato no menyuu o moraemasu ka?" },
  { category: "ristorante", it: "Abbiamo finito.", ja: "ごちそうさまでした。", romaji: "Gochisousama deshita." },
  { category: "ristorante", it: "Paghiamo separatamente.", ja: "別々に払います。", romaji: "Betsubetsu ni haraimasu." },

  // 🛍️ SHOPPING
  { category: "shopping", it: "Quanto costa questo?", ja: "これはいくらですか？", romaji: "Kore wa ikura desu ka?" },
  { category: "shopping", it: "Posso provarlo?", ja: "試着してもいいですか？", romaji: "Shichaku shite mo ii desu ka?" },
  { category: "shopping", it: "Avete una taglia più grande?", ja: "もう少し大きいサイズはありますか？", romaji: "Mou sukoshi ookii saizu wa arimasu ka?" },
  { category: "shopping", it: "Lo prendo.", ja: "これにします。", romaji: "Kore ni shimasu." },
  { category: "shopping", it: "Avete questo in un altro colore?", ja: "これの別の色はありますか？", romaji: "Kore no betsu no iro wa arimasu ka?" },
  { category: "shopping", it: "È troppo costoso.", ja: "高すぎます。", romaji: "Takasugimasu." },
  { category: "shopping", it: "C'è uno sconto?", ja: "割引はありますか？", romaji: "Waribiki wa arimasu ka?" },
  { category: "shopping", it: "Vorrei restituire questo.", ja: "これを返品したいです。", romaji: "Kore o henpin shitai desu." },
  { category: "shopping", it: "Ecco lo scontrino.", ja: "レシートはこちらです。", romaji: "Reshiito wa kochira desu." },
  { category: "shopping", it: "Accettate pagamenti in contanti?", ja: "現金で払えますか？", romaji: "Genkin de haraemasu ka?" },
  { category: "shopping", it: "Cerco un regalo per mia moglie.", ja: "妻へのプレゼントを探しています。", romaji: "Tsuma e no purezento o sagashite imasu." },
  { category: "shopping", it: "Mi può fare un pacchetto regalo?", ja: "ギフト用に包んでくれますか？", romaji: "Gifuto you ni tsutsunde kuremasu ka?" },
  { category: "shopping", it: "A che ora chiudete?", ja: "何時に閉まりますか？", romaji: "Nanji ni shimarimasu ka?" },
  { category: "shopping", it: "Dove posso trovare un bancomat?", ja: "ATMはどこですか？", romaji: "ATM wa doko desu ka?" },

  // 🏨 HOTEL
  { category: "hotel", it: "Ho una prenotazione.", ja: "予約しています。", romaji: "Yoyaku shite imasu." },
  { category: "hotel", it: "Vorrei fare il check-in.", ja: "チェックインをお願いします。", romaji: "Chekkuin o onegaishimasu." },
  { category: "hotel", it: "A che ora è la colazione?", ja: "朝食は何時ですか？", romaji: "Choushoku wa nanji desu ka?" },
  { category: "hotel", it: "Non c'è acqua calda.", ja: "お湯が出ません。", romaji: "Oyu ga demasen." },
  { category: "hotel", it: "La prenotazione è a nome Rossi.", ja: "予約はロッシの名前でしています。", romaji: "Yoyaku wa Rosshi no namae de shite imasu." },
  { category: "hotel", it: "Vorrei una camera per due notti.", ja: "2泊分の部屋をお願いします。", romaji: "Nihaku bun no heya o onegaishimasu." },
  { category: "hotel", it: "La camera è troppo rumorosa.", ja: "部屋がうるさすぎます。", romaji: "Heya ga urusasugimasu." },
  { category: "hotel", it: "L'aria condizionata non funziona.", ja: "エアコンが動きません。", romaji: "Eakon ga ugokimasen." },
  { category: "hotel", it: "Potete pulire la mia stanza adesso?", ja: "今、部屋の掃除をお願いできますか？", romaji: "Ima, heya no souji o onegai dekimasu ka?" },
  { category: "hotel", it: "Mi può svegliare alle 7 domani mattina?", ja: "明日の朝7時に起こしてくれますか？", romaji: "Ashita no asa shichiji ni okoshite kuremasu ka?" },
  { category: "hotel", it: "Posso lasciare qui i miei bagagli?", ja: "ここに荷物を預けてもいいですか？", romaji: "Koko ni nimotsu o azukete mo ii desu ka?" },
  { category: "hotel", it: "C'è una palestra nell'hotel?", ja: "ホテルにジムはありますか？", romaji: "Hoteru ni jimu wa arimasu ka?" },
  { category: "hotel", it: "Mi serve un asciugamano in più.", ja: "追加のタオルをお願いします。", romaji: "Tsuika no taoru o onegaishimasu." },
  { category: "hotel", it: "Avete il servizio in camera?", ja: "ルームサービスはありますか？", romaji: "Ruumu saabisu wa arimasu ka?" },
  
  // 🚨 EMERGENZE
  { category: "emergenze", it: "Aiuto!", ja: "助けて！", romaji: "Tasukete!" },
  { category: "emergenze", it: "Ho bisogno di un medico.", ja: "医者が必要です。", romaji: "Isha ga hitsuyou desu." },
  { category: "emergenze", it: "Chiami un'ambulanza!", ja: "救急車を呼んでください！", romaji: "Kyuukyuusha o yonde kudasai!" },
  { category: "emergenze", it: "Ho perso il mio passaporto.", ja: "パスポートをなくしました。", romaji: "Pasupooto o nakushimashita." },
  { category: "emergenze", it: "Fermati!", ja: "止まれ！", romaji: "Tomare!" },
  { category: "emergenze", it: "Attenzione!", ja: "危ない！ / 気をつけて！", romaji: "Abunai! / Ki o tsukete!" },
  { category: "emergenze", it: "Mi hanno rubato il portafoglio.", ja: "財布を盗まれました。", romaji: "Saifu o nusumaremashita." },
  { category: "emergenze", it: "Dove si trova l'ambasciata italiana?", ja: "イタリア大使館はどこですか？", romaji: "Itaria taishikan wa doko desu ka?" },
  { category: "emergenze", it: "Ho mal di testa.", ja: "頭が痛いです。", romaji: "Atama ga itai desu." },
  { category: "emergenze", it: "Ho mal di stomaco.", ja: "お腹が痛いです。", romaji: "Onaka ga itai desu." },
  { category: "emergenze", it: "Ho la febbre.", ja: "熱があります。", romaji: "Netsu ga arimasu." },
  { category: "emergenze", it: "Ho bisogno di medicine.", ja: "薬が必要です。", romaji: "Kusuri ga hitsuyou desu." },
  { category: "emergenze", it: "Sono incinta.", ja: "妊娠しています。", romaji: "Ninshin shite imasu." },
  { category: "emergenze", it: "Ho perso la mia famiglia.", ja: "家族とはぐれました。", romaji: "Kazoku to haguremashita." }
];